{{ if not .Values.existing_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  AUTH_USERNAME: {{ .Values.auth.username | b64enc | quote }}
  AUTH_PASSWORD: {{ .Values.auth.password | b64enc | quote }}
{{ end }}