  
version: 2
jobs:
  build:
    docker:
      - image: alpine/helm:3.2.4
    steps:
      - checkout
      - run:
          name: helm-github-pages
          environment:
            - GITHUB_PAGES_REPO: capchriscap/helm-charts
            - GITHUB_PAGES_BRANCH: master
            - HELM_CHART: tekton-pipeline-listener
            - HELM_CHART_FOLDER: helm
          entrypoint: sh
          command: wget -O - https://gist.githubusercontent.com/CapChrisCap/ab86d84f3ff1f98000f6af914bd128fb/raw/4a86f01abfa50fe46c1b8026d8d73b07b32eb151/helm_publish.sh | sh
