  
version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-github-pages
          environment:
            - GITHUB_PAGES_REPO: capchriscap/helm-charts
            - GITHUB_PAGES_BRANCH: master
            - HELM_CHART: tekton-pipeline-listener
            - HELM_CHART_FOLDER: helm
            - HELM_VERSION: 3.1.2
          command: wget -O - https://gist.githubusercontent.com/CapChrisCap/ab86d84f3ff1f98000f6af914bd128fb/raw/ecedd34a0032ceeaa08a1759e068bd3a15fc3484/helm_publish.sh | sh