  
version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-github-pages
          environment:
            - GITHUB_PAGES_REPO: capchriscap/helm-charts
            - HELM_CHART: tekton-pipeline-listener
            - HELM_VERSION: 3.1.2
          command: wget -O - https://gist.githubusercontent.com/CapChrisCap/ab86d84f3ff1f98000f6af914bd128fb/raw/ee2e78be63195d4c366ae1275a0c6e60d77e747f/helm_publish.sh| sh